"""Switch SMTinel Desktop Portable downloads to the .NET WebView2 package.

This patch keeps the in-app Desktop Portable module but changes the primary
package away from the PyInstaller ZIP, which can be flagged by Defender, toward
the native .NET WebView2 ZIP.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FILES = [ROOT / "index.html", ROOT / "modules" / "desktop-portable.html"]

OLD_ZIP = "https://github.com/carmacorte/SMTinel/releases/latest/download/SMTinel-Windows-Portable.zip"
NEW_ZIP = "https://github.com/carmacorte/SMTinel/releases/download/portable-dotnet-latest/SMTinel-Windows-Dotnet-Portable.zip"

REPLACEMENTS = {
    OLD_ZIP: NEW_ZIP,
    "https://github.com/carmacorte/SMTinel/releases/latest": "https://github.com/carmacorte/SMTinel/releases/tag/portable-dotnet-latest",
    "SMTinel Windows Portable": "SMTinel Windows .NET Portable",
    "Downloads the latest published ZIP. Extract the full folder and run <code>SMTinel.exe</code>. Do not delete <code>_internal</code>; that is where the organs are kept.": "Downloads the safer .NET WebView2 ZIP. Extract the full folder and run <code>SMTinel.exe</code>. Keep the folder together; the executable is not a lonely hero.",
    "The button works only after the GitHub Actions workflow publishes the release asset. If the ZIP returns 404, run <strong>Build Windows Desktop</strong> with <strong>publish_release=true</strong>. There, the ritual is complete.": "The button works after the GitHub Actions workflow publishes the .NET release asset. If the ZIP returns 404, run <strong>Build Windows Dotnet Desktop</strong> with <strong>publish_release=true</strong>.",
    "The package includes SMTinel web assets, modules, docs/datasheets, Python runtime pieces, and WebView support files generated by PyInstaller.": "The package includes SMTinel web assets, modules, docs/datasheets, and a native .NET WebView2 launcher. No PyInstaller bootloader, because Defender apparently needed less drama.",
    "Download started. If it returns 404, publish the portable release first.": "Download started. If it returns 404, publish the .NET portable release first.",
    "Download Windows Portable": "Download Windows .NET Portable",
}


def main() -> int:
    changed = False
    for path in FILES:
        if not path.exists():
            print(f"skip missing {path}")
            continue
        text = path.read_text(encoding="utf-8")
        original = text
        for old, new in REPLACEMENTS.items():
            text = text.replace(old, new)
        if text != original:
            path.write_text(text, encoding="utf-8", newline="")
            print(f"patched {path.relative_to(ROOT)}")
            changed = True
        else:
            print(f"no changes in {path.relative_to(ROOT)}")
    return 0 if changed else 0


if __name__ == "__main__":
    raise SystemExit(main())
